blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://muhammad-fiaz.github.io/api.zig/
    about: Check out the documentation for guides and API reference
  - name: Discussions
    url: https://github.com/muhammad-fiaz/api.zig/discussions
    about: Ask questions and discuss ideas
